CREATE DATABASE Business;
USE Business;
CREATE TABLE VENDOR 
(Vno INTEGER NOT NULL, 
Vname VARCHAR(20),
City VARCHAR(20),
Vbal DECIMAL(10,2),
PRIMARY KEY (Vno) );

CREATE TABLE CUSTOMER
(AccNum INTEGER NOT NULL,
Cname VARCHAR(20) NOT NULL,
Prov VARCHAR(20),
Cbal DECIMAL(6,2) NOT NULL,
Climit DECIMAL(4,0) NOT NULL,
PRIMARY KEY (AccNum) );

CREATE TABLE TRANSACTIONS
(Tno INTEGER NOT NULL,
Vno INTEGER NOT NULL,
AccNum INTEGER NOT NULL,
Tdate DATE,
Amount DECIMAL(6,2) NOT NULL,
PRIMARY KEY (Tno),
FOREIGN KEY (Vno) REFERENCES VENDOR(Vno),
FOREIGN KEY (AccNum) REFERENCES CUSTOMER(AccNum) );
